var data = {
    man_all: [
        {
            name: '周伟',
            avatar: 'images/zhouwei.png',
        }, {
            name: '陈少芳',
            avatar: 'images/chenshaofang.png',
        }, {
            name: '陈宇哲',
            avatar: 'images/chenyuzhe.png',
        }, {
            name: '江育麟',
            avatar: 'images/jiangyulin.png',
        }, {
            name: '柯宇楠',
            avatar: 'images/keyunan.png',
        }, {
            name: '张彦蔚',
            avatar: 'images/zhangyanwei.png',
        }, {
            name: '刘克亮',
            avatar: 'images/liukeliang.png',
        }, {
            name: '罗云志',
            avatar: 'images/luoyunzhi.png',
        }, {
            name: '王斌',
            avatar: 'images/wangbin.png',
        }, {
            name: '吴亮亮',
            avatar: 'images/wuliangliang.png',
        }, {
            name: '汪金叶',
            avatar: 'images/wangjinye.png',
        }, {
            name: '王潇',
            avatar: 'images/wangxiao.png',
        }, {
            name: '谢进帅',
            avatar: 'images/xiejinshuai.png',
        }, {
            name: '李心骋',
            avatar: 'images/lixincheng.png',
        }, {
            name: '黄志坡',
            avatar: 'images/huangzhipo.png',
        }, {
            name: '陈锦东',
            avatar: 'images/chenjindong.png',
        }, {
            name: '齐晓海',
            avatar: 'images/qixiaohai.png',
        }, {
            name: '黄哲宇',
            avatar: 'images/default.png',
        }, {
            name: '张晶',
            avatar: 'images/default.png',
        }, {
            name: '林玮琦',
            avatar: 'images/default.png',
        }, {
            name: '李汉见',
            avatar: 'images/lihanjian.png',
        },
    ],
    women_all: [
        {
            name: '杨洁',
            avatar: 'images/yangjie.png',
        }, {
            name: '林素娜',
            avatar: 'images/linsuna.png',
        }, {
            name: '张嘉炜',
            avatar: 'images/zhangjiawei.png',
        }, {
            name: '叶颖诗',
            avatar: 'images/yeyinshi.png',
        }, {
            name: '陈施如',
            avatar: 'images/chenshiru.png',
        }, {
            name: '曹哲',
            avatar: 'images/caozhe.png',
        }, {
            name: '刘诗婷',
            avatar: 'images/liushiting.png',
        }, {
            name: '李文慧',
            avatar: 'images/liwenhui.png',
        }, {
            name: '李晓芬',
            avatar: 'images/lixiaofen.png',
        }, {
            name: '杜梦澜',
            avatar: 'images/dumenglan.png',
        }, {
            name: '肖杨',
            avatar: 'images/xiaoyang.png',
        }, {
            name: '许晓薇',
            avatar: 'images/xuxiaowei.png',
        }, {
            name: '彭敬嫦',
            avatar: 'images/pengjingchang.png',
        }, {
            name: '李嘉纯',
            avatar: 'images/lijiachun.png',
        }, {
            name: '胡月伶',
            avatar: 'images/lijiachun.png',
        },
    ]
}
